# Generated by Django 6.0.5 on 2026-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buisness_name', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
