# Generated by Django 6.0.5 on 2026-06-01 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.cafeteriadata')),
            ],
        ),
    ]
