# Generated by Django 6.0.5 on 2026-06-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_cafeteriaproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriadata',
            name='company_logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
