# Generated by Django 6.0.5 on 2026-06-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_cafeteriadata_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriadata',
            name='company_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
