# Generated by Django 6.0.5 on 2026-06-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_alter_cafeteriadata_company_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CafeteriaProduct',
        ),
    ]
