# Generated by Django 6.0.5 on 2026-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='busyness_status',
            field=models.CharField(default='quiet', max_length=10),
        ),
    ]
