# Generated by Django 6.0.5 on 2026-06-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdata_brand_name_alter_studentdata_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
