# Generated by Django 6.0.5 on 2026-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='profile/'),
        ),
    ]
