# Generated by Django 6.0.5 on 2026-06-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='matric_number',
            field=models.CharField(max_length=13),
        ),
    ]
